---
- hosts: all
  become: yes
  roles:
    - role: 'ansible-cassandra'
      cassandra_base_data_dir: "/var/lib/cassandra"
      cassandra_log_dir: "/var/log/cassandra"
      cassandra_config_dir: "/etc/cassandra"
